apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "platops-product-infrastructure"
  description: Product infrastructure for platops
  annotations:
    # This must match folder-name/job-name in Jenkins.
    jenkins.io/job-full-name: cft:HMCTS_platops/test-product-infra-00
    github.com/project-slug: 'hmcts-test/test-product-infra-00'
  tags:
    - terraform
  links:
    - url: https://hmcts-reform.slack.com/app_redirect?channel=cloud-native
      title: cloud-native on Slack
      icon: chat
spec:
  type: service
  system: platops
  lifecycle: experimental
  owner: dts_platform_operations
